### PR TITLE
[ERE-1595] Django 3

### PR DESCRIPTION
**Pull request by ScriptSmith**

### CODE REVIEW

**Comment by ScriptSmith** [comment]
Relevant release notes:

- https://docs.djangoproject.com/en/dev/releases/3.0/
- https://docs.djangoproject.com/en/dev/releases/3.1/
- https://docs.djangoproject.com/en/dev/releases/3.2/

I'd recommend running with `PYTHONWARNINGS=a` in `.env_local` to see all the deprecation warnings.
Currently there's a low-priority warning for X-ray, and warnings for django-useraudit.

I've updated to Python 3.9 & Django 3.2, outstanding tasks for Python 3.10 & Django 4.0 as detailed in the ticket are:
- graphene-django not being supported
- nose & django-nose being deprecated
- django-useraudit's use of signals and `url` rather than `re_path`

You may need to rebuild all of the docker images:

```
docker-compose -f docker-compose-teststack-base.yml -f docker-compose-teststack-dev.yml -f docker-compose-aloe.yml -f docker-compose-selenium.yml -f docker-compose.yml build
```

**Comment by ppettitau** [comment]
Looks good. 

Got another couple of warnings in addition to those mentioned in your comment:
**Explorer**
```
runserver_1    | /app/rdrf/explorer/views.py:100: RemovedInDjango40Warning: request.is_ajax() is deprecated. See Django 3.1 release notes for more details about this deprecation.
runserver_1    |   if request.is_ajax():
```

**Clinician Others**
(This might be existing?)
```
runserver_1    | 172.19.0.1 - - [06/May/2022 07:38:25] "GET /admin/patients/clinicianother/1/change/ HTTP/1.1" 200 -
runserver_1    | /usr/local/lib/python3.9/site-packages/django/utils/translation/trans_real.py:146: RuntimeWarning: localedirs is ignored when domain is 'django'.
runserver_1    |   warnings.warn("localedirs is ignored when domain is 'django'.", RuntimeWarning)
```

Tested - 
* New Reports
* Old Reports
* Registration
* Modifying an existing user (consents and cdes)
* Uploaded a file
* Clinician Other
* Import/Export of a registry
* Plus other general clicking around the site.

**Review by ppettitau — APPROVED** [review]

**Review by ppettitau — CHANGES_REQUESTED** [review]
Tentatively approved pending reply to additional warnings in my prev comment.

**Comment by ScriptSmith** [comment]
Thanks @ppettitau, will add that to the ticket

**Comment by ppettitau** [comment]
Some more warnings:
```
runserver_1    | /usr/local/lib/python3.9/site-packages/botocore/compat.py:31: DeprecationWarning: 'urllib3[secure]' extra is deprecated and will be removed in a future release of urllib3 2.x. Read more in this issue: https://github.com/urllib3/urllib3/issues/2680


runserver_1    | /usr/local/lib/python3.9/site-packages/botocore/httpsession.py:41: DeprecationWarning: 'urllib3.contrib.pyopenssl' module is deprecated and will be removed in a future release of urllib3 2.x. Read more in this issue: https://github.com/urllib3/urllib3/issues/2680
runserver_1    |   from urllib3.contrib.pyopenssl import orig_util_SSLContext as SSLContext


runserver_1    | /usr/local/lib/python3.9/site-packages/django/apps/registry.py:91: RemovedInDjango41Warning: 'aws_xray_sdk.ext.django' defines default_app_config = 'aws_xray_sdk.ext.django.apps.XRayConfig'. Django now detects this configuration automatically. You can remove default_app_config.


runserver_1    | /usr/local/lib/python3.9/site-packages/django/core/management/base.py:254: RemovedInDjango41Warning: Using a boolean value for requires_system_checks is deprecated. Use '__all__' instead of True, and [] (an empty list) instead of False.

```

**Pull request merged**
