### PR TITLE
[TRRFFDA-488] Code formatting

### PR DESCRIPTION
**Pull request by ScriptSmith**

### CODE REVIEW

**Comment by ScriptSmith** [comment]
WIP.

Ignoring the line length and complexity has been disabled, and the linting script passes. I'm still working on other formatting changes, and a `.git-ignore-revs` file

**Comment by sztamas** [comment]
@ScriptSmith Can you please put WIP in the title of PRs that aren't ready to be reviewed yet?
Then remove the WIP when you're done and can be reviewed...
Makes it easier when looking at the PR list.

Thanks

**Comment by ScriptSmith** [comment]
Ok, no worries

**Comment by ScriptSmith** [comment]
I've used 2-spaced indentation in the templates because there are a lot of nested elements, but if it's better to have 4 spaces for readability, we can use that instead.

**Comment by sztamas** [comment]
This grew into a very large set of changes.
Timing when to do changes of this size is always important.

I don't think it would be a good idea to do it before the Angelman merge because it would make that unnecessarily hard.

**Comment by ScriptSmith** [comment]
Ok, that makes sense. We can delay until then.

**Pull request closed without merging**
