### PR TITLE
[ERE-1968] Patients missing new fixed context

### PR DESCRIPTION
**Pull request by ScriptSmith**
Create new fixed contexts for patient on the patient list, in the patient edit view, and in registry form view

### CODE REVIEW

**Comment by ppettitau** [comment]
Works well when I create a new CFG, but if I delete an existing one, I get `Exception: could not determine current index!`

```
runserver_1    |   File "/usr/local/lib/python3.9/site-packages/django/contrib/staticfiles/handlers.py", line 76, in __call__
runserver_1    |     return self.application(environ, start_response)
runserver_1    |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/wsgi.py", line 133, in __call__
runserver_1    |     response = self.get_response(request)
runserver_1    |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 130, in get_response
runserver_1    |     response = self._middleware_chain(request)
runserver_1    |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 49, in inner
runserver_1    |     response = response_for_exception(request, exc)
runserver_1    |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 114, in response_for_exception
runserver_1    |     response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
runserver_1    |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 149, in handle_uncaught_exception
runserver_1    |     return debug.technical_500_response(request, *exc_info)
runserver_1    |   File "/usr/local/lib/python3.9/site-packages/django_extensions/management/technical_response.py", line 40, in null_technical_500_response
runserver_1    |     raise exc_value.with_traceback(tb)
runserver_1    |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
runserver_1    |     response = get_response(request)
runserver_1    |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
runserver_1    |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
runserver_1    |   File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
runserver_1    |     return self.dispatch(request, *args, **kwargs)
runserver_1    |   File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
runserver_1    |     return handler(request, *args, **kwargs)
runserver_1    |   File "/app/rdrf/rdrf/views/form_view.py", line 446, in get
runserver_1    |     wizard = NavigationWizard(self.user,
runserver_1    |   File "/app/rdrf/rdrf/forms/navigation/wizard.py", line 46, in __init__
runserver_1    |     self._construct_links()
runserver_1    |   File "/app/rdrf/rdrf/forms/navigation/wizard.py", line 99, in _construct_links
runserver_1    |     self.current_index = self._determine_current_index()
runserver_1    |   File "/app/rdrf/rdrf/forms/navigation/wizard.py", line 187, in _determine_current_index
runserver_1    |     raise Exception("could not determine current index!")
runserver_1    | Exception: could not determine current index!
```

**Comment by ScriptSmith** [comment]
@ppettitau what were the circumstances? I just tried this with a new fixed context and the only way I could get this error was to visit a deleted cfg through browser history (I'll still look into trying to handle this more gracefully)

**Comment by ppettitau** [comment]
@ScriptSmith Yes I think I must have just refreshed the patient form which would have been for the CFG just deleted. Sorry! disregard.

**Review by ppettitau — APPROVED** [review]
Looks good. Nice to have this fixed 👍

**Comment by ScriptSmith** [comment]
The issue stems from RDRFContext's FK to ContextFormGroup which sets to null on delete: https://github.com/eresearchqut/trrf/blob/3445ed077466678a8abf30baa8634c36cbcf0337/rdrf/rdrf/models/definition/models.py#L1247

I don't know we want to change this because of data loss concerns, so we could look at raising an exception when retrieving the RDRFContext here: https://github.com/eresearchqut/trrf/blob/3445ed077466678a8abf30baa8634c36cbcf0337/rdrf/rdrf/db/contexts_api.py#L113-L120

**Pull request merged**
