### PR TITLE
[TRRFFDA-490] Link carer to patient

### PR DESCRIPTION
**Pull request by alintreznai**

### CODE REVIEW

**Comment by sztamas** [comment]
@alintreznai made some changes to this one.
Please have a look and let me know if it looks ok or not.

_I regenerated an existing migration so you will have to un-apply and apply it again._

Additional questions:

- Carers should have `Patient List` in the menu
- `Add Patient` button should probably be disabled for carers

**Comment by alintreznai** [comment]
@sztamas 
I don't think carers need to have `Patient List` in the menu as that is the default page when they log in when they have multiple patients assigned so when clicking home that page is displayed.

**Comment by sztamas** [comment]
> @sztamas
> I don't think carers need to have `Patient List` in the menu as that is the default page when they log in when they have multiple patients assigned so when clicking home that page is displayed.

@alintreznai 
I think we should add the menu.

- It would be consistent with how it works for clinicians or other types of users as well.
- It is more explicit, not sure if it that obvious to all users that  clicking the project title will take you back to the patient list in case you went to another page
- there will probably be other carer specific pages coming as suggested by Catherine

**Comment by alintreznai** [comment]
Added support code the patients list menu for carer. The actual changes are in the MND PR.

**Review by sztamas — APPROVED** [review]

**Comment by sztamas** [comment]
Error, when trying to save Primary Carer on Demographics page.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 486, in get_or_create
    return self.get(**lookup), False
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 397, in get
    raise self.model.DoesNotExist(
mnd.models.PrimaryCarerRelationship.DoesNotExist: PrimaryCarerRelationship matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/contrib/staticfiles/handlers.py", line 65, in __call__
    return self.application(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/wsgi.py", line 142, in __call__
    response = self.get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 78, in get_response
    response = self._middleware_chain(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 125, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/usr/local/lib/python3.8/site-packages/django_extensions/management/technical_response.py", line 37, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/rdrf/rdrf/rdrf/views/patient_view.py", line 739, in post
    self.all_forms_valid(forms)
  File "/app/mnd/mnd/views/mnd_patient_view.py", line 123, in all_forms_valid
    instance = forms[key].save(commit=False)
  File "/app/mnd/mnd/registry/patients/mnd_admin_forms.py", line 159, in save
    pc, _ = PrimaryCarerRelationship.objects.get_or_create(carer=self.instance, patient=self.patient)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 488, in get_or_create
    return self._create_object_from_params(lookup, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 522, in _create_object_from_params
    obj = self.create(**params)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 413, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 668, in save
    raise ValueError(
ValueError: save() prohibited to prevent data loss due to unsaved related object 'carer'.
```

**Comment by sztamas** [comment]
Please also resolve conflicts and can you try to make the user experience a bit better?

Some points to consider:

The menu should be something more general then `Carer Registration` as we're not using it only to register carers anymore. Maybe something like `Carer Management` or just `Primary Carer`.

On the Demographics page the email is read-only but the field isn't grayed out.
I would also not use a red message underneath it, that can be confused with an error and the explanation could be better instead of the: "You can't change the email address the primary carer while it is linked, even if deactivated !" What does that mean?

The `Carer Management` page should be user-friendlier.
Currently, all you have is a button with the possible action. For example: Link carer: <Carerr>.
In this case, the page should have better explanations than this. Remember that this page will be used by patients, not even an admin who might be more familiar with the carer terminology and functionality.

For this case, the page should explain that you have entered the following person as your primary carer (display all the details from demograhics).
However, the carer isn't currently registered in the system and therefore won't be able to view and edit data on you behalf.
Would you like to invite your carer to use the system?
You can send them an invitation by email by clicking this button.
Please be aware that this give the carer rights to view and edit all your details in the system.

The page should look similar in all the other cases. Explain the current situation, what actions could you take and what those actions will do in detail.
For example, if a primary carer isn't entered in demographics and you access the page, currently you get something that looks like an error message with a not too detailed explanation.
Instead, we shouldn't be showing something that resembles an error message at all, we should just explain that you didn't enter the details of your Primary Carer yet. You can provide the details on the <link>Demographics page</link> if you wish.

... and so on for all the other cases.

**Pull request merged**
