### PR TITLE
[TRRFFDA-325] Create customisable interactive sliders

### PR DESCRIPTION
**Pull request by alintreznai**

### CODE REVIEW

**Review by sztamas — CHANGES_REQUESTED** [review]
Some issues, bugs:

Admin interface - slider configuration:

- Console warning: bootstrap-slider.min.js:5 bootstrap-slider.js - WARNING: $.fn.slider namespace is already bound. Use the $.fn.bootstrapSlider namespace instead.
- Set widget to SliderWidget to make the settings appear. Then change to "x".  The setting disappear but there is a `<br />` that remains
- Set widget to SliderWidget to make the settings appear. Changing the name to something else works, but completely clearing it, leaves the settings in place (404 on the ajax call)
- We should add help text for the Min and Max value, saying leave empty if you want to use the CDE's min and max value
- Change  data type of min, max, and step HTML inputs to be numbers
- Validation:
    - Make sure that you receive and save only what you expect to prevent someone from POSTing in junk
    - Enforce SliderWidget being used only for numeric fields?
    - min, max, step are the right data type
    - min smaller than max, both between min and max of the CDE, step makes sense for min and max

Registry Forms - slider:

- the help text of the CDE is displayed right next to the right label instead of being under the widget
- I created a section with one float CDE, set it to SliderWidget, set it to a value, Saved successfully, but then on reload the slider is set to Min value (0 in this case).
- I think it would be better to change the slider to _always_ display the tooltip with the value, so you see to what it is set without having to hover over

**Comment by alintreznai** [comment]
> _- Console warning: bootstrap-slider.min.js:5 bootstrap-slider.js - WARNING: $.fn.slider namespace is already bound. Use the $.fn.bootstrapSlider namespace instead._

This is more of an informational message. As we're also using bootrap, that library has  a function bound to the $.fn.slider so $.fn.bootstrapSlider needs to be used instead.

> _-Set widget to SliderWidget to make the settings appear. Then change to "x". The setting disappear but there is a br that remains_

Cannot reproduce.

**Comment by sztamas** [comment]
> > - Console warning: bootstrap-slider.min.js:5 bootstrap-slider.js - WARNING: $.fn.slider namespace is already bound. Use the $.fn.bootstrapSlider namespace instead.
> 
> This is more of an informational message. As we're also using bootrap, that library has a function bound to the $.fn.slider so $.fn.bootstrapSlider needs to be used instead.

OK, that's uglyish from them but fine. I thought it is warning because we're not setting it up correctly.

> > -Set widget to SliderWidget to make the settings appear. Then change to "x". The setting disappear but there is a br that remains
> 
> Cannot reproduce.

OK, it is not a `<br>` as I thought, but there is an extra line.
It is actually the bottom-border of the `<div class="form-row field-widget_settings">`. You should hide that instead of the contents of it to solve the issue.

**Comment by sztamas** [comment]
- If the CDE's data type is integer the min/max/step should be integers as well.
- The min/max value of the slider widget shouldn't be allowed to be outside the values permitted for the CDE.
- There is no help text on min/max that makes it clear that the user can leave them empty if they've set the min and max on the CDE itself.

**Comment by alintreznai** [comment]
Implemented the changes.

**Review by sztamas — APPROVED** [review]

**Pull request merged**
