### PR TITLE
[TRRFFDA-554] Redesign the footer

### PR DESCRIPTION
**Pull request by ScriptSmith**

### CODE REVIEW

**Comment by ScriptSmith** [comment]
The base templates are now using flexbox to make the footer 'stick' to the bottom without using a fixed position and potentially obscuring content.

On pages with not a lot of content, the footer will appear at the bottom of the viewport, with a gap between the page content and the footer. On pages with content that extends beyond the viewport, the footer appears at the end of the page, and won't be visible unless scrolled to.

Changes:
- Moved the footer blocks inside the `#wrap` divs
- Changed `#wrap`  to `display: flex`
- Updated the way the footer lays out its row contents to be responsive
- Replaced the broken glyphicon wih a valid one
- Fix invalid markup in base templates

**Comment by ScriptSmith** [comment]
The only other side-effect I've noticed is that the patient list page content is now full width.

**Review by alintreznai — APPROVED** [review]
LGTM

**Review by sztamas — APPROVED** [review]

**Comment by sztamas** [comment]
@ScriptSmith good work!

I made a few changes:

- reverted back the patients list table back to non full-width, as it looked a bit strange especially on wider displays
- removed the glyphicon before the Version - I think it looks better without it
- changed the copyright in the QUT line from 2013 to 2018, as TRRF has been started in that year
- adjusted the text-align in the footer to take account for the padding of 20px as well, the layout was incorrect between 970px and 990px.

**Pull request merged**
