### PR TITLE
[TRRFFDA-547] Change filter appearance so that page content isn't obstructed

### PR DESCRIPTION
**Pull request by ScriptSmith**

### CODE REVIEW

**Comment by alintreznai** [comment]
There is an issue when using a filter which returns no records. The filter section disappears because the displayed template is the old one: change_list.html.
To get around that I think you can add back the block_filters section in there with an additional condition:

 {% block filters %}
      {% if cl.has_filters and not cl.result_count %}
       ....
      {% endif %}
  {% endblock %}

It's also worth mentioning that filters will appear only for admin classes which have the list_filter property set.

**Comment by ScriptSmith** [comment]
Thanks @alintreznai. I've moved it back into the `change_list` template.

I'm a little confused about the `cl.has_filters and not cl.result_count` condition. Doesn't that hide the filter interface if there are results?

**Comment by alintreznai** [comment]
> Thanks @alintreznai. I've moved it back into the `change_list` template.
> 
> I'm a little confused about the `cl.has_filters and not cl.result_count` condition. Doesn't that hide the filter interface if there are results?

Yes it does but since you had it in the other template this would only make it appear for the cases when there were no filtering results, the other cases would be handled by the template where you moved the block. 

I see now that you moved back the filters block to the original template so I guess it should be all fine.

**Comment by alintreznai** [comment]
Tested with the latest changes and it works fine. 
One thing to mention: Filters are only visible for admin classes which have the `list_filter` property set which I guess is by design.

**Review by sztamas — APPROVED** [review]

**Pull request merged**
